### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cihangir** [koding/tf_zookeeper#4]
- [ ] update s3 bucket name
- [ ]  use newly created bucket name in deploy
- [ ]  use newly created aws credentials in deploy
